### PR TITLE
little refactoring and fix for tab index

### PR DESCRIPTION
**Pull request by simllll**
fixes https://github.com/Flam3rboy/puppeteer-stream/issues/41

### CODE REVIEW

**Comment by Flam3rboy** [comment]
thank you for your contribution, however you use the ``getTargetInfo`` function which is not available in puppeteer

**Comment by simllll** [comment]
Ah right, sorry for this, I'm using puppeteer 15, there is this the only valid option. We could feature detect it :-) i will add a commit next week for it

**Comment by Full-Stack-Shokhboz-Abdullayev** [comment]
Hello, I was also facing the same issue with tabs, is there any news?

**Comment by Flam3rboy** [comment]
Thank you very much for taking time to make the PR.
I've tested it, added two type fixes and reformatted the code.

The updated version is published under version `2.1.3`

```
npm i puppeteer-stream@2.1.3
```

**Pull request merged**
